# .travis.yml
env:
  global:
    secure: "i9TsESPUaytcKK4NYOtKgQuiKwvwyRKRqnCWJ9GUBmN7nnk6LeOeD63qFDhF3Kyap9Vkml2Ky6Dzg1enWYOsvCs+8Mb+0ZGbUGGn86cGSYQauOscH3BzMZBLKYon7LzPY183ucoT83E4gHxlnzpf43B+UvwLsnWUf6h8FRhknuk+Ff6AgEDct1bDGNwJITWCnS75Q4q6Wl3GtTusZtFe2oHhgcYpsWa6u7/b8PfAoCsxu5FeYbaRUWmUYAFqSuTJfUvVnGRGraNGaWosIV6yeYpJMco4kkdZH46ReAU1aGRTobrYEpiA2kzmhVDuWHiK+75sItHeQMHENGztfxaPGPT61L6t2r51MXJBKzCq9Xe2Er5/fK7vgL6fzBCLrY2A3ICIxwmMJgRUEl7k+0ED9ezdUMgWfGU/LQZ1XWgpYB+DKC1ZJ+19NoswBJAWe3SUVvkSV+I+NYoMVGPwR73qIDglUXwyR7Ol4uRlQrIBGH+xjK4RdSQbZIPGM+fK9unJgD1k3SWD1QQSc0/BXY52KN/VkJpsUL0uV2YoYv/uvxh5OHZP+9PVfz6+7jxUUJw4iha0rMNb+R4kqpR9yjSOYvEP58ctSGtaDWkIiAI7wpS2oib2eTxhQe1Vtfdq/aLCfhThZYzflWWkueFxFNnRQ27dMCPLz9NfByQUfcxz1Ec="

language: go

go:
  - "1.10"

before_install:
  - go get github.com/mattn/goveralls
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - $HOME/gopath/bin/goveralls -v -service=travis-ci

services:
  - docker

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
#  - mkdir -p dist
#  - CGO_ENABLED="0" GOARCH="amd64" GOOS="linux" go build -a -installsuffix cgo -o ./dist/gomotics
#  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#  - export REPO=$DOCKER_USER/gomotics
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
#  - echo $REPO:$TAG
#  - docker build -f Dockerfile -t $REPO:$TAG .
#  - docker push $REPO