apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    run: elasticsearch
spec:
  type: LoadBalancer
  ports:
  - name: elasticsearch
    port: 9200
    targetPort: 9200
  selector:
    run: elasticsearch