apiVersion: v1
kind: Service
metadata:
  name: ui-nginx
  labels:
    run: ui-nginx
spec:
  type: LoadBalancer
  ports:
  - name: ui-nginx
    port: 80
    targetPort: 80
  selector:
    run: ui-nginx
